apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vetes-scheduler.fullname" . }}
  labels:
    {{- include "vetes-scheduler.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vetes-scheduler.fullname" . }}
  labels:
    {{- include "vetes-scheduler.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vetes-scheduler.fullname" . }}
  labels:
    {{- include "vetes-scheduler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vetes-scheduler.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vetes-scheduler.fullname" . }}
    namespace: {{ .Release.Namespace }}
