run:
  concurrency: 4
  deadline: 5m

linter-settings:
  goimports:
    local-prefixes: "github.com/GBA-BI/tes-scheduler"
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
  - ginkgolinter
  - gocritic
  - govet
  - goconst
  - gofmt
  - goimports
  - ineffassign
  - misspell
  - unparam
  - unused

issues:
  exclude-use-default: false
  exclude-rules:
  - path: _test.go
    linters:
    - errcheck
