blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/GBA-BI/bioos-tes/discussions
    about: If your issue is not a feature request or bug report use Bio-OS tes Dissusion